### ISSUE TITLE
本地node执行iqiyi.js报错，已添加环境变量到iQIYI_COOKIE和SEND_KEY

### ISSUE THREAD

**Issue by lqrqw** [BlueskyClouds/My-Actions#47]
运行日志如下，请问是不是cookie的问题呢？已经添加环境变量到iQIYI_COOKIE，同样配置腾讯视频的环境变量，v_video.js能正常签到。 

奇艺会员签到, 开始!
下载代码完毕
替换变量完毕
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /jd/scripts/iQIYI.js:121:26
    at Request._callback (/jd/scripts/iQIYI.js:274:9)
    at Request.self.callback (/jd/scripts/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/jd/scripts/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/jd/scripts/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:3069) UnhandledPromiseRejectionWarning: Error: Command failed: node iQIYI.js >> result.txt
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /jd/scripts/iQIYI.js:121:26
    at Request._callback (/jd/scripts/iQIYI.js:274:9)
    at Request.self.callback (/jd/scripts/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/jd/scripts/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/jd/scripts/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at start (/jd/scripts/iqiyi.js:49:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BlueskyClouds** [comment]
解决了？
