### ISSUE TITLE
腾讯视频突然异常了，重新获取cookie也一样

### ISSUE THREAD

**Issue by qingyu0725** [BlueskyClouds/My-Actions#54]
🔔腾讯视频会员签到, 开始!
25
/home/runner/work/My-Actions/My-Actions/function/v_video.js:70
26
            notice += "腾讯视频会员任务领取：微信登录可能无法领取任务,签到正常，可能是Cookie更新出现问题。待排查。" + "\n"
27
            ^
28

29
ReferenceError: notice is not defined
30
    at getAuth (/home/runner/work/My-Actions/My-Actions/function/v_video.js:70:13)
31
    at Object.<anonymous> (/home/runner/work/My-Actions/My-Actions/function/v_video.js:13:14)
32
    at Module._compile (internal/modules/cjs/loader.js:778:30)
33
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
34
    at Module.load (internal/modules/cjs/loader.js:653:32)
35
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
36
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
37
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
38
    at startup (internal/bootstrap/node.js:283:19)
39
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
40
Error: Process completed with exit code 1.

**Comment by BlueskyClouds** [comment]
一会改一下。

**Comment by BlueskyClouds** [comment]
同步一下就好了。

**Comment by qingyu0725** [comment]
谢谢了
